
const products = [
  {
    id: 1,
    name: "Modern Chesterfield 3-Seater Sofa – Faux Leather",
    price: 285000,
    oldPrice: 420000,
    image: "https://m.media-amazon.com/images/I/8108kcQAkaL._AC_UF894,1000_QL80_.jpg",
    category: "Sofas & Living Room",
    description: "Elevate your living room with this stunning Modern Chesterfield 3-Seater Sofa. Crafted with premium faux leather upholstery, this sofa combines classic elegance with contemporary comfort. The deep button-tufted back and rolled arms create a timeless look that suits any home décor.",
    dimensions: "Length: 220cm | Depth: 85cm | Height: 75cm",
    stock: 15
  },
  {
    id: 2,
    name: "Contemporary Living Room Sofa Set (3+2)",
    price: 395000,
    oldPrice: null,
    image: "https://www.coasterfurniture.com/wp-content/uploads/gano-living-room-set.png",
    category: "Sofas & Living Room",
    description: "Transform your living space with this elegant Contemporary Living Room Sofa Set. This 3+2 combination includes a spacious 3-seater and a cozy 2-seater, perfect for family gatherings and entertaining guests. Modern design meets exceptional comfort.",
    dimensions: "3-Seater: 200cm x 85cm x 80cm | 2-Seater: 150cm x 85cm x 80cm",
    stock: 8
  },
  {
    id: 3,
    name: "9-Piece Extendable Dining Table Set – Solid Wood",
    price: 480000,
    oldPrice: 650000,
    image: "https://m.media-amazon.com/images/I/818vNipOGKL.jpg",
    category: "Dining Sets",
    description: "Host memorable dinner parties with this magnificent 9-Piece Extendable Dining Table Set. Crafted from solid wood, this set includes one extendable dining table and eight matching chairs. The rich finish adds warmth and sophistication to your dining area.",
    dimensions: "Table: 180-220cm x 100cm x 76cm | Chair: 45cm x 50cm x 95cm",
    stock: 5
  },
  {
    id: 4,
    name: "Queen Size Upholstered Platform Bed – Beige",
    price: 195000,
    oldPrice: null,
    image: "https://m.media-amazon.com/images/I/81imf690CRL._AC_UF894,1000_QL80_.jpg",
    category: "Beds & Bedroom",
    description: "Sleep in style with this luxurious Queen Size Upholstered Platform Bed. The soft beige fabric headboard adds a touch of elegance to your bedroom while providing comfortable back support for reading or watching TV in bed.",
    dimensions: "Length: 210cm | Width: 160cm | Headboard Height: 120cm",
    stock: 12
  },
  {
    id: 5,
    name: "4-Door Sliding Wardrobe with Mirror – Walnut",
    price: 320000,
    oldPrice: 450000,
    image: "https://futonland.com/common/images/products2/large/PI-8206M-WRD-MC.jpg",
    category: "Wardrobes",
    description: "Maximize your storage space with this stunning 4-Door Sliding Wardrobe. The built-in mirrors add depth to your room while serving a practical purpose. The walnut finish brings warmth and sophistication to your bedroom.",
    dimensions: "Width: 250cm | Depth: 60cm | Height: 220cm",
    stock: 6
  },
  {
    id: 6,
    name: "Modern Glass Top Coffee Table with Storage",
    price: 85000,
    oldPrice: null,
    image: "https://www.expressfurniture.net/wp-content/uploads/2021/06/426449_791x633_01.jpg",
    category: "Interior Decor",
    description: "Add a modern touch to your living room with this sleek Glass Top Coffee Table. The tempered glass surface sits atop a stylish base with convenient storage space for magazines, remotes, and decorative items.",
    dimensions: "Length: 120cm | Width: 60cm | Height: 45cm",
    stock: 20
  },
  {
    id: 7,
    name: "Floating TV Stand – 55-65 inch – Oak Finish",
    price: 145000,
    oldPrice: 210000,
    image: "https://m.media-amazon.com/images/S/aplus-media-library-service-media/805c58fd-4f3f-40be-9979-e7be40caf4cd.__CR0,188,1500,1125_PT0_SX800_V1___.jpg",
    category: "Home Entertainment",
    description: "Create a clean, modern look with this Floating TV Stand. Wall-mounted design saves floor space while providing ample storage for your entertainment devices. The oak finish adds natural warmth to your living room.",
    dimensions: "Width: 180cm | Depth: 35cm | Height: 30cm",
    stock: 10
  },
  {
    id: 8,
    name: "Ergonomic Home Office Chair – Mesh Back",
    price: 68900,
    oldPrice: null,
    image: "https://www.content.upliftdesk.com/content/img/product/RAY344/blk.jpg?compression=lossy",
    category: "Office Furniture",
    description: "Work comfortably all day with this Ergonomic Home Office Chair. The breathable mesh back keeps you cool while the adjustable features ensure perfect posture. Ideal for home offices and long working hours.",
    dimensions: "Seat Width: 50cm | Seat Depth: 45cm | Height: 95-105cm",
    stock: 25
  },
  {
    id: 9,
    name: "5-Tier Modern Bookshelf – Oak",
    price: 112000,
    oldPrice: 158000,
    image: "https://m.media-amazon.com/images/S/aplus-media-library-service-media/969f5713-23c1-4057-81fc-033a8cd71c68.__CR0,0,2910,1800_PT0_SX970_V1___.jpg",
    category: "Office Furniture",
    description: "Organize your books and display your favorite items with this 5-Tier Modern Bookshelf. The oak finish and clean lines complement any room style. Perfect for living rooms, home offices, or bedrooms.",
    dimensions: "Width: 80cm | Depth: 30cm | Height: 180cm",
    stock: 14
  },
  {
    id: 10,
    name: "Single Recliner Armchair – Leather Finish",
    price: 165000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
    category: "Sofas & Living Room",
    description: "Relax in ultimate comfort with this Single Recliner Armchair. The leather finish adds a touch of luxury while the reclining mechanism lets you find your perfect relaxation angle. Perfect for reading, watching TV, or afternoon naps.",
    dimensions: "Width: 85cm | Depth: 90-150cm | Height: 100cm",
    stock: 9
  },
  {
    id: 11,
    name: "Modern Chesterfield 3-Seater Sofa – Faux Leather",
    price: 285000,
    oldPrice: 420000,
    image: "https://m.media-amazon.com/images/I/8108kcQAkaL._AC_UF894,1000_QL80_.jpg",
    category: "Sofas & Living Room",
    brand: "LeezWorld Original",
    description: "Elevate your living room with this stunning Modern Chesterfield 3-Seater Sofa. Crafted with premium faux leather upholstery, deep button-tufted back, and rolled arms for timeless elegance and comfort.",
    dimensions: "220cm × 90cm × 85cm",
    stock: 18
  },
  {
    id: 12,
    name: "Contemporary Living Room Sofa Set (3+2) – Gray Fabric",
    price: 395000,
    oldPrice: null,
    image: "https://www.coasterfurniture.com/wp-content/uploads/gano-living-room-set.png",
    category: "Sofas & Living Room",
    brand: "Coaster",
    description: "Spacious and stylish 3+2 sofa set in soft gray fabric. Perfect for family gatherings with plush seating and modern design.",
    dimensions: "3-Seater: 200cm × 85cm × 80cm | 2-Seater: 150cm × 85cm × 80cm",
    stock: 10
  },
  {
    id: 13,
    name: "L-Shaped Sectional Sofa with Chaise – Dark Gray",
    price: 550000,
    oldPrice: 735000,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    category: "Sofas & Living Room",
    brand: "Ashley Furniture",
    description: "Versatile L-shaped sectional with chaise lounge in durable dark gray fabric. Ideal for large families or open-plan living spaces.",
    dimensions: "280cm × 160cm × 85cm (configurable)",
    stock: 7
  },
  {
    id: 14,
    name: "Single Recliner Armchair – Leather Finish Brown",
    price: 165000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
    category: "Sofas & Living Room",
    brand: "Homelegance",
    description: "Comfortable single recliner armchair with rich brown leather finish and smooth manual reclining mechanism.",
    dimensions: "85cm × 90-150cm × 100cm",
    stock: 12
  },
  {
    id: 15,
    name: "Modern 2-Seater Loveseat – Velvet Blue",
    price: 195000,
    oldPrice: 245000,
    image: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800&q=80",
    category: "Sofas & Living Room",
    brand: "LeezWorld Original",
    description: "Elegant 2-seater loveseat in luxurious velvet blue fabric. Perfect accent piece for modern living rooms or cozy corners.",
    dimensions: "150cm × 85cm × 80cm",
    stock: 9
  },
  {
    id: 16,
    name: "Mid-Century Modern 3-Seater Sofa – Mustard Yellow",
    price: 320000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1550254478-ead40cc54513?w=800&q=80",
    category: "Sofas & Living Room",
    brand: "Signature Design",
    description: "Bold mid-century 3-seater sofa in vibrant mustard yellow. Tapered wooden legs and clean lines for a retro-contemporary look.",
    dimensions: "210cm × 80cm × 78cm",
    stock: 6
  },
  {
    id: 17,
    name: "Complete Living Room Set (3+2+1) – Premium Leather",
    price: 680000,
    oldPrice: 970000,
    image: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=800&q=80",
    category: "Sofas & Living Room",
    brand: "Ashley Furniture",
    description: "Luxurious full living room set (3-seater + 2-seater + armchair) in premium black leather. Timeless comfort and high-end style.",
    dimensions: "3-Seater: 220cm × 90cm × 85cm | 2-Seater: 170cm × 90cm × 85cm | Armchair: 90cm × 90cm × 85cm",
    stock: 4
  },
  {
    id: 18,
    name: "Modern Accent Armchair – Fabric Beige",
    price: 89000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800&q=80",
    category: "Sofas & Living Room",
    brand: "LeezWorld Original",
    description: "Versatile modern accent armchair in neutral beige fabric. Sleek design that complements any living room or bedroom setup.",
    dimensions: "75cm × 80cm × 85cm",
    stock: 20
  },
  {
    id: 19,
    name: "U-Shaped Modular Sectional – 7 Seater Gray",
    price: 750000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1567016432779-094069958ea5?w=800&q=80",
    category: "Sofas & Living Room",
    brand: "Coaster",
    description: "Large U-shaped modular sectional sofa for 7 people. Flexible layout in soft gray fabric – ideal for big families or entertaining.",
    dimensions: "350cm × 250cm × 85cm (configurable)",
    stock: 5
  },
  {
    id: 20,
    name: "Scandinavian Style 3-Seater Sofa – Light Gray",
    price: 245000,
    oldPrice: 290000,
    image: "https://images.unsplash.com/photo-1491926626787-62db157af940?w=800&q=80",
    category: "Sofas & Living Room",
    brand: "Signature Design",
    description: "Minimalist Scandinavian 3-seater sofa in light gray. Clean lines and airy feel perfect for modern Nordic-inspired interiors.",
    dimensions: "205cm × 85cm × 78cm",
    stock: 11
  },
  {
    id: 21,
    name: "Power Reclining Sofa with USB – Black Leather",
    price: 385000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1558211583-d26f610c1eb1?w=800&q=80",
    category: "Sofas & Living Room",
    brand: "Ashley Furniture",
    description: "Power reclining 3-seater sofa in black leather with built-in USB ports. Ultimate comfort for movie nights or relaxing.",
    dimensions: "220cm × 95-170cm × 100cm",
    stock: 8
  },
  {
    id: 22,
    name: "Storage Ottoman Bench – Velvet Green",
    price: 45000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1519947486511-46149fa0a254?w=800&q=80",
    category: "Sofas & Living Room",
    brand: "LeezWorld Original",
    description: "Stylish velvet green storage ottoman bench. Doubles as extra seating and hidden storage for blankets, remotes, or toys.",
    dimensions: "100cm × 50cm × 45cm",
    stock: 25
  },
  {
    id: 23,
    name: "Modular Corner Sofa – Light Beige Fabric",
    price: 620000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=800&q=80",
    category: "Sofas & Living Room",
    brand: "LeezWorld Original",
    description: "Flexible modular corner sofa in light beige fabric. Customizable layout with deep seating and modern design – perfect for large living spaces.",
    dimensions: "320cm × 220cm × 85cm (configurable)",
    stock: 6
  },
  {
    id: 24,
    name: "Grey Fabric Sectional Sofa with Chaise – 5 Seater",
    price: 580000,
    oldPrice: 780000,
    image: "https://images.unsplash.com/photo-1512212621149-107ffe572d2f?w=800&q=80",
    category: "Sofas & Living Room",
    brand: "Ashley Furniture",
    description: "Spacious 5-seater sectional with chaise in soft grey fabric. Reversible chaise and plush cushions for ultimate comfort and flexibility.",
    dimensions: "300cm × 180cm × 85cm",
    stock: 5
  },
  {
    id: 25,
    name: "Velvet Green 3-Seater Sofa – Tufted Back",
    price: 410000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1550581190-9c1c48d21d6c?w=800&q=80",
    category: "Sofas & Living Room",
    brand: "Signature Design",
    description: "Elegant 3-seater sofa in rich velvet green with classic tufted back design. Luxurious texture and deep seating for a sophisticated living room.",
    dimensions: "210cm × 90cm × 85cm",
    stock: 8
  },
 {
    id: 26,
    name: "8-Seater Solid Wood Dining Table – Natural Brown",
    price: 480000,
    oldPrice: 650000,
    image: "https://m.media-amazon.com/images/I/51cSjmsCEKL._AC_UF894,1000_QL80_.jpg",
    category: "Dining Sets",
    brand: "LeezWorld Original",
    description: "Elegant 8-seater solid wood dining table with rich natural brown finish. Sturdy legs and smooth surface make it perfect for large family meals or gatherings.",
    dimensions: "240cm × 100cm × 76cm",
    stock: 8
  },
  {
    id: 27,
    name: "6-Seater Modern Dining Set – White with Wood Accents",
    price: 420000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80",
    category: "Dining Sets",
    brand: "Coaster",
    description: "Sleek modern 6-seater dining set in crisp white with warm wood accent legs. Clean lines and contemporary design brighten any dining space.",
    dimensions: "Table: 180cm × 90cm × 75cm | Chairs: 45cm × 50cm × 95cm",
    stock: 12
  },
  {
    id: 28,
    name: "4-Seater Round Wooden Dining Set – Light Oak",
    price: 320000,
    oldPrice: 390000,
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&q=80",
    category: "Dining Sets",
    brand: "Ashley Furniture",
    description: "Cozy round 4-seater dining set in light oak finish. Space-saving circular design with comfortable chairs – ideal for small to medium dining areas.",
    dimensions: "Table diameter: 120cm × 76cm | Chairs: 45cm × 50cm × 90cm",
    stock: 10
  },
  {
    id: 29,
    name: "6-Seater Rustic Farmhouse Table – Reclaimed Wood",
    price: 520000,
    oldPrice: null,
    image: "https://i.etsystatic.com/7407610/r/il/58f2df/4039016457/il_fullxfull.4039016457_kgws.jpg",
    category: "Dining Sets",
    brand: "Signature Design",
    description: "Authentic rustic farmhouse 6-seater dining table made from reclaimed wood. Distressed finish adds character and warmth to casual or farmhouse-style dining rooms.",
    dimensions: "200cm × 100cm × 78cm",
    stock: 7
  },
  {
    id: 30,
    name: "4-Seater Minimalist Dining Set – Scandinavian White",
    price: 280000,
    oldPrice: 360000,
    image: "https://cdn.decorilla.com/online-decorating/wp-content/uploads/2023/06/Scandinavian-dining-room-with-light-wood-tones.jpg?width=900",
    category: "Dining Sets",
    brand: "LeezWorld Original",
    description: "Minimalist 4-seater dining set in bright Scandinavian white. Clean, airy design with light wood tones – perfect for modern Nordic or contemporary homes.",
    dimensions: "Table: 140cm × 80cm × 75cm | Chairs: 42cm × 48cm × 90cm",
    stock: 9
  },
  {
    id: 31,
    name: "8-Seater Elegant Formal Dining Set – Dark Walnut",
    price: 780000,
    oldPrice: null,
    image: "https://m.media-amazon.com/images/I/818vNipOGKL.jpg",
    category: "Dining Sets",
    brand: "Homelegance",
    description: "Sophisticated 8-seater formal dining set in deep dark walnut finish. Classic detailing and luxurious feel – ideal for elegant dining rooms.",
    dimensions: "Table: 240cm × 110cm × 76cm | Chairs: 48cm × 52cm × 98cm",
    stock: 5
  },
  {
    id: 32,
    name: "6-Seater Glass Top Dining Table – Chrome Base",
    price: 290000,
    oldPrice: 450000,
    image: "https://cdn11.bigcommerce.com/s-3uyyclsi/images/stencil/original/products/509/8156/CR110401-S5_21-1__75716.1724256294.jpg?c=2",
    category: "Dining Sets",
    brand: "LeezWorld Original",
    description: "Modern 6-seater dining set with clear tempered glass top and polished chrome base. Opens up the space visually and adds a sleek contemporary touch.",
    dimensions: "Table: 180cm × 90cm × 75cm | Chairs: 45cm × 50cm × 92cm",
    stock: 11
  },
  {
    id: 33,
    name: "6-Seater Industrial Dining Set – Metal & Wood",
    price: 380000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?w=800&q=80",
    category: "Dining Sets",
    brand: "Coaster",
    description: "Bold industrial 6-seater dining set combining black metal frame with natural wood top. Urban loft style with rugged yet stylish appeal.",
    dimensions: "Table: 190cm × 95cm × 76cm | Chairs: 44cm × 50cm × 90cm",
    stock: 8
  },
  {
    id: 34,
    name: "4-Seater Round Marble Top Dining Set – Gold Base",
    price: 460000,
    oldPrice: null,
    image: "https://www.lunafurn.com/cdn/shop/files/Vida-6-Piece-White-Marble-Dining-Set-Table-4-Side-Chairs-Luna-Furniture-27076204429366.jpg?v=1768306987&width=1645",
    category: "Dining Sets",
    brand: "Signature Design",
    description: "Luxurious round 4-seater dining set with elegant white marble top and shiny gold base. Sophisticated centerpiece for modern or upscale dining rooms.",
    dimensions: "Table diameter: 130cm × 76cm | Chairs: 46cm × 50cm × 95cm",
    stock: 6
  },
  {
    id: 35,
    name: "6-8 Seater Extendable Dining Table – Modern White",
    price: 380000,
    oldPrice: 620000,
    image: "https://images.unsplash.com/photo-1615066390971-03e4e3400c09?w=800&q=80",
    category: "Dining Sets",
    brand: "Ashley Furniture",
    description: "Versatile extendable dining table (6–8 seats) in clean modern white finish. Leaf extension for extra guests – ideal for flexible family dining.",
    dimensions: "160–220cm × 90cm × 75cm (extended)",
    stock: 9
  },
  {
    id: 36,
    name: "4-Seater Kitchen Breakfast Nook Set – Natural Wood",
    price: 310000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    category: "Dining Sets",
    brand: "LeezWorld Original",
    description: "Cozy 4-seater breakfast nook set in warm natural wood. Compact and functional design – perfect for kitchens or small dining areas.",
    dimensions: "Table: 120cm × 80cm × 75cm | Benches/Chairs: built-in style",
    stock: 14
  },
  {
    id: 37,
    name: "6-Seater Contemporary Dining Set – Warm Walnut",
    price: 350000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=800&q=80",
    category: "Dining Sets",
    brand: "Coaster",
    description: "Elegant 6-seater contemporary dining set in rich warm walnut finish. Clean lines, comfortable chairs, and timeless appeal for everyday dining.",
    dimensions: "Table: 180cm × 90cm × 76cm | Chairs: 45cm × 50cm × 94cm",
    stock: 10
  },
  {
    id: 38,
    name: "6-Seater Mid-Century Dining Set – Teak Wood",
    price: 720000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1597072689227-8882273e8f6a?w=800&q=80",
    category: "Dining Sets",
    brand: "Ashley Furniture",
    description: "Mid-century modern 6-seater dining set in premium teak wood. Tapered legs and organic shapes create a warm, timeless dining experience.",
    dimensions: "Table: 190cm × 95cm × 75cm | Chairs: 44cm × 48cm × 90cm",
    stock: 5
  },
  {
    id: 39,
    name: "6-Seater Outdoor Patio Dining Set – Weather Resistant",
    price: 420000,
    oldPrice: 600000,
    image: "https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=800&q=80",
    category: "Dining Sets",
    brand: "Signature Design",
    description: "Durable 6-seater outdoor patio dining set built to withstand weather. Stylish and practical for balconies, terraces, gardens or poolside dining.",
    dimensions: "Table: 180cm × 90cm × 75cm | Chairs: 46cm × 52cm × 90cm",
    stock: 7
  },
  {
    id: 40,
    name: "8-Seater Luxury Dining Set – Velvet Upholstered Chairs",
    price: 1250000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=80",
    category: "Dining Sets",
    brand: "Homelegance",
    description: "Opulent 8-seater luxury dining set with plush velvet-upholstered chairs. Grand scale, elegant detailing, and high-end comfort for formal dining.",
    dimensions: "Table: 260cm × 110cm × 78cm | Chairs: 50cm × 55cm × 100cm",
    stock: 4
  },
  {
    id: 41,
    name: "King Size Platform Bed – Upholstered Gray Fabric",
    price: 380000,
    oldPrice: 510000,
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&q=80",
    category: "Beds & Bedroom",
    brand: "LeezWorld Original",
    description: "Sleek king-size platform bed with soft gray upholstered headboard and low-profile frame. Modern minimalist design with excellent mattress support and clean lines for contemporary bedrooms.",
    dimensions: "210cm × 200cm × 35cm (platform height) | Headboard: 120cm",
    stock: 9
  },
  {
    id: 42,
    name: "Queen Size Wooden Bed Frame – Natural Walnut Finish",
    price: 295000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1588046130717-0eb0c9a3ba15?w=800&q=80",
    category: "Beds & Bedroom",
    brand: "Ashley Furniture",
    description: "Elegant queen-size wooden bed frame in warm natural walnut finish. Sturdy solid wood construction with timeless panel headboard – perfect for classic or transitional bedrooms.",
    dimensions: "Queen: 205cm × 160cm × 35cm | Headboard: 110cm height",
    stock: 12
  },
  {
    id: 43,
    name: "Complete Bedroom Set – King Bed + 2 Nightstands White",
    price: 720000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80",
    category: "Beds & Bedroom",
    brand: "Signature Design",
    description: "Luxurious 3-piece bedroom set including king platform bed and two matching nightstands in crisp white finish. Modern design with ample storage and clean aesthetic.",
    dimensions: "Bed: 210cm × 200cm × 35cm | Nightstands: 50cm × 40cm × 60cm each",
    stock: 5
  },
  {
    id: 44,
    name: "Queen Tufted Headboard Bed – Velvet Navy Blue",
    price: 345000,
    oldPrice: 495000,
    image: "https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=800&q=80",
    category: "Beds & Bedroom",
    brand: "Homelegance",
    description: "Sophisticated queen bed with deep tufted navy blue velvet headboard. Luxurious texture and elegant button detailing – ideal for romantic or upscale bedroom setups.",
    dimensions: "Queen: 205cm × 160cm × 40cm | Headboard: 130cm height",
    stock: 8
  },
  {
    id: 45,
    name: "King Storage Bed with 4 Drawers – Oak Finish",
    price: 420000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1617325247661-675ab4b64ae2?w=800&q=80",
    category: "Beds & Bedroom",
    brand: "LeezWorld Original",
    description: "Practical king-size storage bed with 4 spacious drawers for blankets, linens, or seasonal clothing. Oak finish with modern platform design – maximizes bedroom space.",
    dimensions: "210cm × 200cm × 45cm (with drawers) | Headboard: 110cm",
    stock: 7
  },
  {
    id: 46,
    name: "Queen Minimalist Metal Bed Frame – Matte Black",
    price: 125000,
    oldPrice: 210000,
    image: "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&q=80",
    category: "Beds & Bedroom",
    brand: "Coaster",
    description: "Sleek minimalist queen metal bed frame in matte black finish. Simple, sturdy design with no headboard – perfect for modern industrial or Scandinavian bedrooms.",
    dimensions: "Queen: 205cm × 160cm × 30cm",
    stock: 15
  },
  {
    id: 47,
    name: "Luxury 5-Piece Bedroom Set – King Bed + Dresser + Mirror",
    price: 1450000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80",
    category: "Beds & Bedroom",
    brand: "Ashley Furniture",
    description: "Complete luxury 5-piece bedroom set including king bed, dresser, mirror, and two nightstands. Elegant design with premium finishes – transforms any bedroom into a high-end retreat.",
    dimensions: "Bed: 210cm × 200cm × 40cm | Dresser: 150cm × 45cm × 90cm",
    stock: 4
  },
  {
    id: 48,
    name: "King Floating Platform Bed – Contemporary White",
    price: 485000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800&q=80",
    category: "Beds & Bedroom",
    brand: "Signature Design",
    description: "Ultra-modern king floating platform bed in glossy white. Wall-mounted illusion design creates a spacious, airy feel – perfect for contemporary or minimalist bedrooms.",
    dimensions: "210cm × 200cm × 35cm | Floating height: 10cm from wall",
    stock: 6
  },
  {
    id: 49,
    name: "King Canopy Bed Frame – Romantic Gold Metal",
    price: 520000,
    oldPrice: 650000,
    image: "https://images.unsplash.com/photo-1578898886225-c7c894047899?w=800&q=80",
    category: "Beds & Bedroom",
    brand: "Homelegance",
    description: "Romantic king canopy bed frame in elegant gold metal. Graceful posts and clean lines – ideal for adding drama and luxury to any bedroom.",
    dimensions: "210cm × 200cm × 220cm (canopy height)",
    stock: 5
  },
  {
    id: 50,
    name: "Queen Upholstered Bed – Soft Beige Linen",
    price: 275000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80",
    category: "Beds & Bedroom",
    brand: "LeezWorld Original",
    description: "Cozy queen upholstered bed in soft beige linen fabric. Padded headboard for comfortable back support – simple and inviting design for everyday bedrooms.",
    dimensions: "205cm × 160cm × 40cm | Headboard: 115cm",
    stock: 11
  },
  {
    id: 51,
    name: "King Panel Bed with Headboard – Dark Espresso Wood",
    price: 365000,
    oldPrice: 430000,
    image: "https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800&q=80",
    category: "Beds & Bedroom",
    brand: "Coaster",
    description: "Classic king panel bed in rich dark espresso wood finish. Solid headboard and footboard design – timeless and sturdy for traditional or modern bedrooms.",
    dimensions: "210cm × 200cm × 40cm | Headboard: 130cm",
    stock: 8
  },
  {
    id: 52,
    name: "King Sleigh Bed – Traditional Cherry Wood",
    price: 580000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1558882268-85c1b3f0ede2?w=800&q=80",
    category: "Beds & Bedroom",
    brand: "Ashley Furniture",
    description: "Elegant traditional king sleigh bed in warm cherry wood. Curved headboard and footboard create a sophisticated, timeless look for classic bedrooms.",
    dimensions: "210cm × 200cm × 140cm (headboard height)",
    stock: 6
  },
  {
    id: 53,
    name: "King Modern Platform Bed with LED Lights – White Gloss",
    price: 650000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=800&q=80",
    category: "Beds & Bedroom",
    brand: "Signature Design",
    description: "Futuristic king platform bed in glossy white with built-in LED lights. Modern design with ambient lighting – perfect for contemporary or tech-savvy bedrooms.",
    dimensions: "210cm × 200cm × 35cm | LED strip lighting included",
    stock: 7
  },
  {
    id: 54,
    name: "King Rustic Bed Frame – Reclaimed Barnwood Style",
    price: 310000,
    oldPrice: 480000,
    image: "https://images.unsplash.com/photo-1616627561839-074385245ff6?w=800&q=80",
    category: "Beds & Bedroom",
    brand: "LeezWorld Original",
    description: "Rustic king bed frame made from reclaimed barnwood. Distressed finish adds authentic farmhouse charm – ideal for cozy, natural bedroom designs.",
    dimensions: "210cm × 200cm × 40cm | Headboard: 120cm",
    stock: 9
  },
  {
    id: 55,
    name: "King Wingback Bed – Emerald Green Velvet",
    price: 495000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800&q=80",
    category: "Beds & Bedroom",
    brand: "Homelegance",
    description: "Luxurious king wingback bed in rich emerald green velvet. Tall padded headboard with elegant wings – adds drama and comfort to upscale bedrooms.",
    dimensions: "210cm × 200cm × 150cm (headboard height)",
    stock: 6
  },
  {
    id: 56,
    name: "Premium Walk-in Closet System – White Organization",
    price: 850000,
    oldPrice: null,
    image: "https://s3.amazonaws.com/media.thestowcompany.com/managed_media/filer_public/57/53/575305ee-1f18-4730-836f-80bf14fa1836/ec_703.jpg",
    category: "Wardrobes",
    brand: "Signature Design",
    description: "Complete premium walk-in closet system in clean white finish. Includes adjustable shelves, hanging rails, shoe storage, and drawers for maximum organization and accessibility in master bedrooms.",
    dimensions: "Customizable – typical setup: 300cm × 200cm × 240cm",
    stock: 4
  },
  {
    id: 57,
    name: "3-Door Hinged Wardrobe with Drawers – Classic White",
    price: 320000,
    oldPrice: 450000,
    image: "https://roomanddecor.com/cdn/shop/files/20230703_1151a31407e74831cdd88a7e6ac111e7.jpg?v=1725018522&width=1946",
    category: "Wardrobes",
    brand: "LeezWorld Original",
    description: "Classic 3-door hinged wardrobe in timeless white finish with integrated drawers and generous hanging space. Smooth operation and elegant design – perfect for bedrooms with classic or transitional style.",
    dimensions: "180cm × 60cm × 220cm",
    stock: 8
  },
  {
    id: 58,
    name: "Industrial Open Closet System with Shelves & Rails",
    price: 265000,
    oldPrice: null,
    image: "https://www.thespruce.com/thmb/rmbYdFsfabTrrcHpUUHfbTq6DQc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-14212728751-c8ab1106fd3c45ed92b042e39d38582e.jpg",
    category: "Wardrobes",
    brand: "Ashley Furniture",
    description: "Modern industrial open closet system with black metal frame and natural wood shelves. Open design for easy access, includes hanging rails and multiple storage levels – ideal for loft or urban bedrooms.",
    dimensions: "200cm × 50cm × 220cm",
    stock: 10
  },
  {
    id: 59,
    name: "4-Door Sliding Wardrobe with Mirror – Modern White",
    price: 385000,
    oldPrice: 550000,
    image: "https://www.oppoliahome.com/wp-content/uploads/2022/12/white-wardrobe-with-mirror-obw23-l03.jpg",
    category: "Wardrobes",
    brand: "LeezWorld Original",
    description: "Spacious 4-door sliding wardrobe with full-length mirror in modern white finish. Smooth gliding doors, internal shelving, and hanging rails – maximizes space and adds light reflection to any bedroom.",
    dimensions: "240cm × 60cm × 220cm",
    stock: 7
  },
  {
    id: 60,
    name: "Fitted Built-in Wardrobe with Drawers – Oak Finish",
    price: 520000,
    oldPrice: null,
    image: "https://www.strachan.co.uk/app/uploads/bedroom-verona-english-oak31.jpg",
    category: "Wardrobes",
    brand: "Homelegance",
    description: "Custom-fitted built-in wardrobe in warm oak finish with multiple drawers, hanging sections, and shelves. Seamless wall integration for maximum storage in bedrooms or dressing areas.",
    dimensions: "Customizable – typical: 300cm × 60cm × 240cm",
    stock: 5
  },
  {
    id: 61,
    name: "Walk-in Closet with Shoe Racks & Shelves – Gray",
    price: 420000,
    oldPrice: 525000,
    image: "https://www.idfdesign.com/images/walk-in-closets/walk-in-closet-ak-14-walk-in-closet-3.jpg",
    category: "Wardrobes",
    brand: "Coaster",
    description: "Organized walk-in closet system in contemporary gray tones. Features dedicated shoe racks, adjustable shelves, hanging rails, and island unit – perfect for organized luxury.",
    dimensions: "250cm × 200cm × 240cm",
    stock: 6
  },
  {
    id: 62,
    name: "2-Door Minimalist Sliding Wardrobe – Scandinavian White",
    price: 245000,
    oldPrice: null,
    image: "https://img.interiorcompany.com/interior/webproduct/624638700372367318078.png?aio=w-1200;",
    category: "Wardrobes",
    brand: "Signature Design",
    description: "Clean minimalist 2-door sliding wardrobe in bright Scandinavian white. Smooth operation, simple design, and efficient storage – ideal for small to medium bedrooms.",
    dimensions: "160cm × 60cm × 220cm",
    stock: 11
  },
  {
    id: 63,
    name: "6-Drawer Tall Dresser Chest – Natural Wood",
    price: 285000,
    oldPrice: null,
    image: "https://m.media-amazon.com/images/S/aplus-media-library-service-media/3058f48c-15db-4881-bf79-dd11319831f4.__CR0,0,800,600_PT0_SX800_V1___.png",
    category: "Wardrobes",
    brand: "Ashley Furniture",
    description: "Elegant tall 6-drawer chest in natural wood finish. Ample storage for clothing, accessories, or linens – perfect as a standalone piece or part of a bedroom set.",
    dimensions: "80cm × 45cm × 130cm",
    stock: 9
  },
  {
    id: 64,
    name: "Compact 2-Door Wardrobe for Small Spaces – White",
    price: 125000,
    oldPrice: 195000,
    image: "https://m.media-amazon.com/images/S/aplus-media-library-service-media/bd7e7249-212c-4fd6-9c30-ba1af17df594.__CR0,0,970,600_PT0_SX970_V1___.jpg",
    category: "Wardrobes",
    brand: "LeezWorld Original",
    description: "Space-saving compact 2-door wardrobe in clean white finish. Ideal for apartments, guest rooms, children's rooms, or any area with limited space.",
    dimensions: "100cm × 55cm × 180cm",
    stock: 14
  },
  {
    id: 65,
    name: "Expandable Modular Closet System – Light Oak",
    price: 680000,
    oldPrice: null,
    image: "https://d1b9sdpix36q7o.cloudfront.net/blog-content/blog/wp-content/uploads/2022/06/Sereno_Canyon_Callum_PCloset_3469.jpg",
    category: "Wardrobes",
    brand: "Signature Design",
    description: "Flexible expandable modular closet system in light oak finish. Adjustable shelves, hanging rails, drawers, and customizable layout – perfect for growing storage needs.",
    dimensions: "Expandable – typical: 200–400cm × 60cm × 220cm",
    stock: 5
  },
  {
    id: 66,
    name: "5-Drawer Tall Chest of Drawers – Natural Wood",
    price: 165000,
    oldPrice: null,
    image: "https://m.media-amazon.com/images/S/aplus-media-library-service-media/fff71001-107e-49f9-b0eb-b44766ead29e.__CR0,0,970,600_PT0_SX970_V1___.jpg",
    category: "Wardrobes",
    brand: "Coaster",
    description: "Tall 5-drawer chest in natural wood finish. Versatile storage for clothing, accessories, or bedroom essentials – clean and timeless design.",
    dimensions: "75cm × 40cm × 125cm",
    stock: 10
  },
  {
    id: 67,
    name: "Colorful 2-Door Kids Wardrobe with Shelves",
    price: 118000,
    oldPrice: 140000,
    image: "https://thumbs.dreamstime.com/b/colorful-children-s-clothing-arranged-wardrobe-shelves-vibrant-kids-outfits-neatly-hung-kids-fashion-concept-colorful-children-331503484.jpg",
    category: "Wardrobes",
    brand: "LeezWorld Original",
    description: "Fun and functional 2-door kids wardrobe with colorful accents and internal shelves. Encourages organization while adding playful style to children's rooms.",
    dimensions: "90cm × 55cm × 180cm",
    stock: 13
  },
  {
    id: 68,
    name: "Classic 2-Door Armoire Wardrobe – Cherry Wood",
    price: 345000,
    oldPrice: null,
    image: "https://www.idfdesign.com/images/luxury-classic-wardrobe-closet/piranesi-ra-0830-worked-wardrobes-4.jpg",
    category: "Wardrobes",
    brand: "Homelegance",
    description: "Traditional 2-door armoire wardrobe in rich cherry wood finish. Classic carved details and timeless design – perfect for bedrooms or entryways.",
    dimensions: "110cm × 60cm × 210cm",
    stock: 7
  },
  {
    id: 69,
    name: "4-Door Wardrobe with Frosted Glass Doors – Warm Grey",
    price: 465000,
    oldPrice: 595000,
    image: "https://m.media-amazon.com/images/I/81Z3OBi8JBL.jpg_BO30,255,255,255_UF750,750_SR1910,1000,0,C_QL100_.jpg",
    category: "Wardrobes",
    brand: "Ashley Furniture",
    description: "Modern 4-door wardrobe with elegant frosted glass doors in warm grey finish. Combines visibility, sophistication, and practical storage for contemporary bedrooms.",
    dimensions: "200cm × 60cm × 220cm",
    stock: 6
  },
  {
    id: 70,
    name: "Luxury Master Walk-in Closet System – Premium Gray",
    price: 1250000,
    oldPrice: null,
    image: "https://d1b9sdpix36q7o.cloudfront.net/blog-content/blog/wp-content/uploads/2022/06/Sereno_Canyon_Callum_PCloset_3469.jpg",
    category: "Wardrobes",
    brand: "Signature Design",
    description: "High-end luxury master walk-in closet system in premium gray tones. Extensive shelving, hanging space, island unit, and integrated lighting – designed for organized elegance.",
    dimensions: "Customizable – typical: 350cm × 300cm × 240cm",
    stock: 3
  },
  {
    id: 71,
    name: "Large Round Wall Mirror – Gold Metal Frame 90cm",
    price: 85000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1618220179428-22790b461013?w=800&q=80",
    category: "Interior Decor",
    brand: "LeezWorld Original",
    description: "Elegant large round wall mirror with luxurious gold metal frame. 90cm diameter – perfect as a statement piece above console tables, in entryways or bedrooms.",
    dimensions: "Diameter: 90cm | Frame width: 5cm",
    stock: 12
  },
  {
    id: 72,
    name: "Large Minimalist Wall Clock – Black Silent Movement 50cm",
    price: 28000,
    oldPrice: 38000,
    image: "https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=800&q=80",
    category: "Interior Decor",
    brand: "Signature Design",
    description: "Modern minimalist large wall clock in matte black with silent sweeping movement. 50cm diameter – clean design for living rooms, offices or kitchens.",
    dimensions: "Diameter: 50cm | Depth: 4cm",
    stock: 15
  },
  {
    id: 73,
    name: "Ceramic Table Lamp with Fabric Shade – White & Gold",
    price: 45000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80",
    category: "Interior Decor",
    brand: "Ashley Home",
    description: "Stylish ceramic table lamp with white base, gold accents, and fabric shade. Perfect accent lighting for bedside tables, consoles or living room side tables.",
    dimensions: "Height: 60cm | Shade diameter: 35cm",
    stock: 10
  },
  {
    id: 74,
    name: "Modern Arc Floor Lamp – Marble Base & Brass Finish",
    price: 78000,
    oldPrice: 112000,
    image: "https://images.unsplash.com/photo-1540932239986-30128078f3c5?w=800&q=80",
    category: "Interior Decor",
    brand: "LeezWorld Original",
    description: "Elegant modern arc floor lamp with heavy marble base and brass finish arm. Adjustable height and direction – ideal for reading nooks or living room corners.",
    dimensions: "Height: 180–220cm adjustable | Base diameter: 40cm",
    stock: 8
  },
  {
    id: 75,
    name: "Set of 4 Luxury Throw Pillows – Velvet & Geometric",
    price: 32000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800&q=80",
    category: "Interior Decor",
    brand: "Homelegance",
    description: "Luxurious set of 4 velvet throw pillows with geometric patterns. Soft and plush – perfect for adding texture and color to sofas, beds or accent chairs.",
    dimensions: "45cm × 45cm each",
    stock: 20
  },
  {
    id: 76,
    name: "Hand-Woven Geometric Area Rug – 200x300cm Beige",
    price: 145000,
    oldPrice: 182000,
    image: "https://images.unsplash.com/photo-1600166898405-da9535204843?w=800&q=80",
    category: "Interior Decor",
    brand: "Signature Design",
    description: "Hand-woven geometric area rug in neutral beige tones. Soft texture and durable weave – ideal for living rooms, bedrooms or dining areas.",
    dimensions: "200cm × 300cm",
    stock: 9
  },
  {
    id: 77,
    name: "Modern Ceramic Vase Set of 3 – Minimalist White",
    price: 38000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=800&q=80",
    category: "Interior Decor",
    brand: "LeezWorld Original",
    description: "Minimalist set of 3 white ceramic vases in varying heights. Clean modern design – perfect for displaying dried flowers, branches or as standalone decor.",
    dimensions: "Heights: 25cm, 35cm, 45cm",
    stock: 18
  },
  {
    id: 78,
    name: "Set of 3 Floating Wall Shelves – Rustic Wood",
    price: 42000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1594620302200-9a762244a156?w=800&q=80",
    category: "Interior Decor",
    brand: "Coaster",
    description: "Rustic wood floating wall shelves set of 3. Clean lines and natural finish – great for displaying books, plants, photos or decorative items.",
    dimensions: "Lengths: 60cm, 80cm, 100cm | Depth: 20cm each",
    stock: 14
  },
  {
    id: 79,
    name: "Elegant Marble Top Console Table – Gold Legs",
    price: 125000,
    oldPrice: 148000,
    image: "https://images.unsplash.com/photo-1532372320572-cda25653a26d?w=800&q=80",
    category: "Interior Decor",
    brand: "Ashley Home",
    description: "Sophisticated marble top console table with slim gold metal legs. Perfect for entryways, hallways or behind sofas – adds luxury and elegance.",
    dimensions: "120cm × 40cm × 80cm",
    stock: 7
  },
  {
    id: 80,
    name: "Round Glass Accent Side Table – Gold Frame",
    price: 58000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1499933374294-4584851497cc?w=800&q=80",
    category: "Interior Decor",
    brand: "LeezWorld Original",
    description: "Modern round glass side table with gold metal frame. Sleek and lightweight – ideal as an accent piece next to sofas, chairs or beds.",
    dimensions: "Diameter: 45cm | Height: 55cm",
    stock: 12
  },
  {
    id: 81,
    name: "Gallery Wall Picture Frame Set – 6 Black Frames",
    price: 24000,
    oldPrice: 38000,
    image: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=800&q=80",
    category: "Interior Decor",
    brand: "Signature Design",
    description: "Set of 6 black gallery wall picture frames in mixed sizes. Perfect for creating a personalized photo wall or art display in living rooms or hallways.",
    dimensions: "Various sizes – total layout approx 120cm × 100cm",
    stock: 15
  },
  {
    id: 82,
    name: "Crystal Candle Holder Set of 3 – Elegant Glass",
    price: 28000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1602528495790-96f93f0e5cf6?w=800&q=80",
    category: "Interior Decor",
    brand: "Homelegance",
    description: "Elegant set of 3 crystal glass candle holders. Sparkling faceted design – perfect for dining tables, mantelpieces or as ambient lighting accents.",
    dimensions: "Heights: 15cm, 20cm, 25cm",
    stock: 20
  },
  {
    id: 83,
    name: "3-Tier Bamboo Plant Stand – Indoor Display",
    price: 35000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800&q=80",
    category: "Interior Decor",
    brand: "Coaster",
    description: "Natural bamboo 3-tier plant stand for indoor plants. Lightweight and eco-friendly – great for displaying succulents, herbs or small potted plants.",
    dimensions: "60cm × 40cm × 100cm",
    stock: 11
  },
  {
    id: 84,
    name: "Set of 3 Woven Seagrass Storage Baskets",
    price: 28000,
    oldPrice: 34000,
    image: "https://images.unsplash.com/photo-1591085686350-798c0f9faa7f?w=800&q=80",
    category: "Interior Decor",
    brand: "LeezWorld Original",
    description: "Natural woven seagrass storage baskets set of 3. Versatile for organizing blankets, toys, magazines or plants – adds boho texture to any room.",
    dimensions: "Sizes: 30cm, 40cm, 50cm diameter",
    stock: 16
  },
  {
    id: 85,
    name: "Large Artificial Monstera Plant – 150cm with Pot",
    price: 65000,
    oldPrice: null,
    image: "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=800&q=80",
    category: "Interior Decor",
    brand: "Ashley Home",
    description: "Lifelike large artificial Monstera plant (150cm tall) with realistic leaves and included pot. Low-maintenance greenery – perfect for corners, living rooms or offices.",
    dimensions: "Height: 150cm | Pot diameter: 30cm",
    stock: 13
  },

  {
    id: 86,
    name: "Floating TV Stand with RGB LED Lights – 65-85 inch Matte Black",
    price: 185000,
    oldPrice: null,
    image: "https://m.media-amazon.com/images/I/71AcFMWw9SL._AC_UF894,1000_QL80_.jpg",
    category: "Home Entertainment",
    brand: "LeezWorld Original",
    description: "Modern floating TV stand with built-in RGB LED lights and cable management. Supports 65-85 inch TVs in matte black finish – sleek wall-mounted design for contemporary living rooms.",
    dimensions: "180cm × 40cm × 30cm (floating)",
    stock: 9
  },
  {
    id: 87,
    name: "Full Wall Entertainment Center with Storage – Solid Walnut",
    price: 420000,
    oldPrice: 560000,
    image: "https://dutchcraftfurniture.com/cdn/shop/files/Custom_Solid_Oak_Entertainment_Center.jpg?v=1749808267&width=2000",
    category: "Home Entertainment",
    brand: "Signature Design",
    description: "Luxurious full-wall entertainment center in solid walnut finish. Includes multiple shelves, cabinets, and media compartments – perfect for large TVs and organized storage.",
    dimensions: "300cm × 50cm × 220cm (full wall)",
    stock: 5
  },
  {
    id: 88,
    name: "Modern TV Console with Sliding Barn Doors – White Oak 58 inch",
    price: 145000,
    oldPrice: null,
    image: "https://m.media-amazon.com/images/I/71Fjp7EpazL._AC_UF894,1000_QL80_.jpg",
    category: "Home Entertainment",
    brand: "Ashley Furniture",
    description: "Contemporary 58-inch TV console with sliding barn doors in white oak finish. Open shelves and hidden storage – rustic-modern style for living rooms or media rooms.",
    dimensions: "147cm × 45cm × 70cm",
    stock: 10
  },
  {
    id: 89,
    name: "Corner TV Stand with Open Shelves – Dark Industrial Wood",
    price: 95000,
    oldPrice: 135000,
    image: "https://www.furniturecart.com/media/catalog/product/W/2/W283-67-tv-stand-1.jpg",
    category: "Home Entertainment",
    brand: "LeezWorld Original",
    description: "Space-saving corner TV stand in dark industrial wood finish. Open shelves for components and decor – perfect for smaller rooms or corner placements.",
    dimensions: "110cm × 110cm × 60cm (corner)",
    stock: 12
  },
  {
    id: 90,
    name: "TV Console with Built-in Electric Fireplace – Espresso 50-65 inch",
    price: 385000,
    oldPrice: null,
    image: "https://www.dorelhome.com/cdn/shop/files/2000_2000_13622_4_sourceimage_2048x2048.jpg?v=1751455928",
    category: "Home Entertainment",
    brand: "Homelegance",
    description: "Elegant TV console with realistic built-in electric fireplace. Espresso finish supports 50-65 inch TVs – adds warmth and ambiance to living spaces.",
    dimensions: "150cm × 45cm × 110cm",
    stock: 6
  },
  {
    id: 91,
    name: "Industrial Media Console – Reclaimed Wood & Metal Frame 60 inch",
    price: 128000,
    oldPrice: 160000,
    image: "https://wwmake.com/cdn/shop/products/Two_Shelf_Media_Console_800x.jpg?v=1623732137",
    category: "Home Entertainment",
    brand: "Coaster",
    description: "Rustic-industrial 60-inch media console with reclaimed wood top and black metal frame. Open shelves and sturdy build – perfect for modern loft or urban living rooms.",
    dimensions: "152cm × 45cm × 70cm",
    stock: 9
  },
  {
    id: 92,
    name: "L-Shaped Gaming Desk with RGB LED Lights – Carbon Fiber Black",
    price: 175000,
    oldPrice: null,
    image: "https://m.media-amazon.com/images/I/81sE2NqZq-L._AC_UF894,1000_QL80_.jpg",
    category: "Home Entertainment",
    brand: "Signature Design",
    description: "Large L-shaped gaming desk with RGB LED lighting and carbon fiber texture in black. Multiple levels for monitors, PC, and accessories – ideal for gamers and creators.",
    dimensions: "160cm × 160cm × 75cm (L-shape)",
    stock: 8
  },
  {
    id: 93,
    name: "Modern Media Console with Glass Doors – Gray 60 inch",
    price: 165000,
    oldPrice: null,
    image: "https://hekman.com/cdn/shop/files/yvx0rburugwmrvc1e5jd.jpg?v=1761904725&width=2000",
    category: "Home Entertainment",
    brand: "Ashley Furniture",
    description: "Sleek 60-inch modern media console with tempered glass doors in gray finish. Open shelving and cable management – clean contemporary look for TVs up to 65 inches.",
    dimensions: "152cm × 45cm × 70cm",
    stock: 10
  },
  {
    id: 94,
    name: "Minimalist Floating TV Console – Scandinavian White 55-65 inch",
    price: 85000,
    oldPrice: 130000,
    image: "https://www.maatkastenonline.be/storage/app/resized/550/e91/771/maatkasten-online-meuble-dangle-meuble-tv-sur-mesure-front-white-05b_resized_550e917714d0ecb5d1fa12096a3cebd3e96859fd.jpg",
    category: "Home Entertainment",
    brand: "LeezWorld Original",
    description: "Floating minimalist TV console in Scandinavian white finish. Supports 55-65 inch TVs with hidden cable management – clean, airy design for modern living rooms.",
    dimensions: "160cm × 40cm × 30cm (floating)",
    stock: 11
  },
  {
    id: 95,
    name: "Ergonomic Racing Gaming Chair – Black & Red with Lumbar Support",
    price: 125000,
    oldPrice: null,
    image: "https://m.media-amazon.com/images/I/71y4d-Nt0pL.jpg_BO30,255,255,255_UF750,750_SR1910,1000,0,C_QL100_.jpg",
    category: "Home Entertainment",
    brand: "Homelegance",
    description: "High-back ergonomic racing gaming chair in black & red with adjustable lumbar support and armrests. PU leather and breathable mesh – perfect for long gaming sessions.",
    dimensions: "Seat width: 55cm | Height adjustable: 120–130cm",
    stock: 13
  },
  {
    id: 96,
    name: "Wall-Mounted Floating TV Shelf Panel – High Gloss White",
    price: 195000,
    oldPrice: null,
    image: "https://www.gingkofurniture.com/cdn/shop/products/OsloTV_1600x.jpg?v=1454709502",
    category: "Home Entertainment",
    brand: "Signature Design",
    description: "High-gloss white floating TV shelf panel with wall-mounted design. Clean minimalist look with cable management – supports TVs up to 65 inches.",
    dimensions: "180cm × 40cm × 20cm",
    stock: 8
  },
  {
    id: 97,
    name: "Mid-Century TV Stand with Drawers – Natural Wood 60 inch",
    price: 138000,
    oldPrice: 162000,
    image: "https://www.modernmiami.com/media/catalog/product/cache/6d4faa98f2b48c05dae02148ead85f2f/8/1/81626_662n_jefferson_wall_tv_stand_walnut_grey_1_.jpg",
    category: "Home Entertainment",
    brand: "Coaster",
    description: "Mid-century style 60-inch TV stand in natural wood with drawers and open shelving. Tapered legs and retro design – great for living rooms or media centers.",
    dimensions: "152cm × 45cm × 60cm",
    stock: 9
  },
  {
    id: 98,
    name: "Entertainment Center with Bookshelves – Oak Wall Unit",
    price: 285000,
    oldPrice: null,
    image: "https://www.countrysideamishfurniture.com/media/made/uploads/ridgecrest_3_piece_entertainment_center_-_28de80_-_74aad5d6e3cbd9f279a5c80496e33864583a9f9f.jpg",
    category: "Home Entertainment",
    brand: "LeezWorld Original",
    description: "Spacious oak wall entertainment center with integrated bookshelves and media storage. Traditional design with ample display space – ideal for large TVs and collections.",
    dimensions: "250cm × 50cm × 220cm",
    stock: 6
  },
  {
    id: 99,
    name: "Floating Soundbar Shelf with Cable Management – Black Glass",
    price: 35000,
    oldPrice: 45000,
    image: "https://m.media-amazon.com/images/I/51BCC0042mL.jpg",
    category: "Home Entertainment",
    brand: "Ashley Furniture",
    description: "Sleek floating black glass soundbar shelf with cable management. Wall-mounted design – perfect for clean audio setups under TVs.",
    dimensions: "120cm × 20cm × 10cm",
    stock: 15
  },
  {
    id: 100,
    name: "Luxury Full Wall Entertainment Center – Premium Walnut Finish",
    price: 650000,
    oldPrice: null,
    image: "https://www.countrysideamishfurniture.com/media/made/uploads/newcastle_wall_entertainment_center_-_28de80_-_cad1e64866d25f914f52e15bb9229f71aa1ca25d.jpg",
    category: "Home Entertainment",
    brand: "Signature Design",
    description: "Premium full-wall entertainment center in rich walnut finish. Extensive storage, shelving, and media space – luxury centerpiece for high-end living rooms.",
    dimensions: "350cm × 50cm × 220cm",
    stock: 4
  }
];

// Function to get product by ID
// function getProductById(id) {
//   return products.find(product => product.id === parseInt(id));
// }

// // Function to format price in Naira
// function formatPrice(price) {
//   return "₦" + price.toLocaleString();
// }
